version: '3.3'
services:
    speedtest:
       environment:
           - ENABLE_LETSENCRYPT=True
           - DOMAIN_NAME=speedtest.deepdeyiitk.com
           - USER_EMAIL=deydeep200821@gmail.com
           - VERIFY_OWNERSHIP="Verify.txt"
       restart: unless-stopped
       container_name: openspeedtest
       ports:
            - '80:3000'
            - '443:3001'
       image: openspeedtest/latest
